version: '3.9'
services:
  neo4j:
    image: neo4j:5-community
    environment:
      - NEO4J_AUTH=none
      - NEO4J_server_directories_import=/
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./resources:/resources
